name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Check-format
        run: make check_fmt
      
      - name: Build
        run: make all
      
      - name: Test
        run: make test